### ISSUE TITLE
An FTL first approach to l10n

### ISSUE THREAD

**Issue by dannycoates** [mozilla/testpilot#1717]
Our plan so far for localizing experiment strings is an extension to our yaml files, beautifully implemented by Chuck in #1708. It's a practical approach, but not without some limitations and annoyances. I know it's late to be proposing a different solution, but the discussion on Friday got me thinking more deeply about it.

Here I explore the concept of keeping our human visible strings in [FTL format](https://github.com/l20n/l20n.js/blob/master/docs/syntax.rst). You can view the live result of this experiment here: http://dcoates-testpilot.s3-website-us-west-2.amazonaws.com

There's an FTL file for each experiment. Here's a portion of the `universal-search.ftl` with comments:

``` makefile
# FTL allows us to use stable static data-l10n-ids in the app while
# being able to update strings with new versions of text.

# One way to do this is with variants:

# 'title' is the stable id used in the app. The default variant marker (*)
# allows us to toggle between different strings.
title =
 *[acquired] NBC Universal Search
  [original] Universal Search

# Another method is with references:

# 'description' is the stable id, which references the current prefered string
original-description =
  | Get recommendations for the best sites on the web
  | as you type in the Awesome Bar.
description = { original-description }

#### Different methods of changing strings for array items ####

# Create a new id when changing the string:
detail-caption-1 = Popular sites, people and Wikipedia articles appear as you type.
detail-caption-2 = If you will it, it is no dream
detail-caption-2-explicit = You're out of your element

# the code references data-l10n-id="details" data-l10n-args="{ index: 1 }"
details = { $index ->
  [0] { detail-caption-1 }
  [1] { detail-caption-2-explicit }
}

# Or use variants:
tour-caption =
  [step1] You can now search and navigate in one place.
  [step2] Recommendations for popular sites and Wikipedia articles will appear as you type.
  [step3] You can always give us feedback or disable Universal Search from Test Pilot.

tour-steps = { $index ->
  [0] { tour-caption[step1] }
  [1] { tour-caption[step2] }
  [2] { tour-caption[step3] }
}
```

From the web app these files are included and given a name corresponding to the `slug`

``` html
<link rel="localization" name="universal-search" href="/static/locales/{locale}/universal-search.ftl">
```

Referencing an experiment's `data-l10n-id`s is done by specifying the `data-l10n-bundle`, for example:

``` jsx
<p data-l10n-id="description" data-l10n-bundle={ slug }></p>
```

and also the `data-l10n-args` for lists:

``` jsx
<div className="details-list">
  {details.map((detail, index) => (
   <div key={index}>
     <div className="details-image">
       <img width="680" src={detail} />
       <p className="caption"><span data-l10n-id="details" data-l10n-bundle={ slug } data-l10n-args={JSON.stringify({ index })}></span></p>
     </div>
   </div>
  ))}
</div>
```

Now it's possible¹ to remove those text fields completely from the yaml:

``` yml
# title is kept for use by the addon
title: 'Universal Search'
slug: universal-search
thumbnail: /static/images/experiments/universal-search/experiments_experiment/a/8/a8182b008f6434ba702ab177232625e2_thumbnail_1461818424_0011.png
version: 1.0.6
changelog_url: 'https://github.com/mozilla/universal-search/blob/master/docs/changelog.md'
contribute_url: 'https://github.com/mozilla/universal-search'
bug_report_url: 'https://github.com/mozilla/universal-search/issues'
discourse_url: 'https://discourse.mozilla-community.org/c/test-pilot/universal-search'
privacy_notice_url: 'https://github.com/mozilla/universal-search/blob/master/docs/metrics.md'
xpi_url: 'https://s3-us-west-2.amazonaws.com/universal-search/universal-search.xpi'
addon_id: universal-search@mozilla.com
gradient_start: '#01BDAD'
gradient_stop: '#01A39D'
details:
  - /static/images/experiments/universal-search/experiments_experimentdetail/6/d/6d0ff50eff9223f0d0cc58c5aa5d0c81_image_1462827811_0995.jpg
  - /static/images/experiments/universal-search/experiments_experimentdetail/8/6/8675c7bf31054abdaf58b47850a1365d_image_1462827811_0451.jpg
tour_steps:
  - /static/images/experiments/universal-search/experiments_experimenttourstep/e/b/eb1a0c8bbb18c79f63d0df45d165eb7a_image_1462826805_0035.jpg
  - /static/images/experiments/universal-search/experiments_experimenttourstep/5/2/5218821d5851bef5ad979da5830f68b2_image_1462826805_0031.jpg
  - /static/images/experiments/universal-search/experiments_experimenttourstep/1/d/1d414ba2fc88a188b6f74ea79de908e9_image_1462826805_0789.jpg
contributors:
  -
    display_name: 'Nick Chapman'
    title: product-manager
    avatar: /static/images/experiments/universal-search/avatars/nick-chapman.jpg
  -
    display_name: 'Bryan Bell'
    title: senior-ux-designer
    avatar: /static/images/experiments/universal-search/avatars/bryan-bell.jpg
  -
    display_name: 'Jared Hirsch'
    title: staff-engineer
    avatar: /static/images/experiments/universal-search/avatars/jared-hirsch.jpg
  -
    display_name: 'Chuck Harmston'
    title: senior-engineer
    avatar: /static/images/experiments/universal-search/avatars/chuck-harmston.jpg
created: '2016-04-28T03:57:32.270681Z'
modified: '2016-07-20T15:42:28.873321Z'
order: 7
locales:
  - 'en'
```

The full changeset for this concept is here: https://github.com/dannycoates/testpilot/commit/6e2c5de2b5a8505f0ef7a1794660ec29caf3668a

The main advantages I see to this approach over yaml are:
- A better separation of concerns
- No l10n specific logic in the app
- The full power of FTL for translators

It'd be nice to have a single file for each experiment. A next step might be to pull all the data from yaml into the ftl and run a transform step to generate the json and final (sanitized) ftl files. We'll also probably want to explore better integration between l20n.js and React, which there's already an [issue](https://github.com/mozilla/testpilot/issues/1714) open for.

attn: @chuckharmston @lmorchard @6a68 

---

_¹We may want to keep them for other reasons_
