### ISSUE TITLE
Permit experiments to opt out of Heartbeat-style Test Pilot prompts.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#2107]
Pulse will be prompting users about their experiences with websites using a Heartbeat-style prompt:

<img width="479" alt="screen shot 2017-01-30 at 3 05 32 pm" src="https://cloud.githubusercontent.com/assets/23885/22443874/cb8a981c-e6fd-11e6-95c6-634537d87358.png">

There's potential for confusion with the Test Pilot prompts asking for users' experience with experiments (which don't really apply to Pulse anyway, since it doesn't introduce a feature). It'd be great if those can be opted out of on a per-experiment basis.

**Comment by chuckharmston** [comment]
Offer myself as a reviewer!

**Comment by dannycoates** [comment]
I'm thinking something like this in the experiment yml:

```yml
dev: true
id: 999
title: 'Dev Example'
slug: dev-example
thumbnail: /static/images/check.png
testpilot_options:
  ratings: false
description: >
  This is an example experiment that you should never see in production.
...
```

what do you think?
