### ISSUE TITLE
Tweak CSS to only output certain vendor prefixes?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#327]
Per [idea-town/idea_town/frontend/static-src/styles/_base.scss:12-18](https://github.com/mozilla/idea-town/blob/fe24e1c41e9b3e77800db186cbbbc1bb7dc57cb8/idea_town/frontend/static-src/styles/_base.scss#L12-L18), we get something like the generated CSS (via Sass and our [AutoPrefixer](https://github.com/mozilla/idea-town/blob/fe24e1c41e9b3e77800db186cbbbc1bb7dc57cb8/gulpfile.js#L112) task):
### INPUT:

``` css
body {
  box-sizing: border-box;
  display: flex;
  flex-direction: column;
  font-family: 'Open Sans', sans-serif;
  font-size: 1.6rem;
}
```
### OUTPUT:

``` css
body {
  box-sizing: border-box;
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column;
  font-family: 'Open Sans', sans-serif;
  font-size: 1.6rem; }
```
### AUTOPREFIXER CONFIG:

``` js
.pipe(autoprefixer('last 2 versions'))
```

If we're only intending for this site to be used by Firefox browsers, not sure if we want to strip out the `-webkit-` and `-ms-` prefixes.
