### ISSUE TITLE
Provide a visual indicator that a link will take the user off of the Test Pilot domain.

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#972]
e.g. Discourse, surveys, etc.

From the June usability research, but lower priority.

**Comment by pdehaan** [comment]
This may be pretty easy if we do something like this: https://css-tricks.com/attribute-selectors/
There were two approaches that could be super easy:
1. Manually add `rel="external"` to any `<a>` tags in our HTML templates to mark any URLs that go to external sites (such as GitHub, Discourse, etc). Then we just do some CSS like this to change appearance or add trailing icons, etc:
   
   ``` sass
   a[rel="external"] { color: red; }
   ```
   
   **PROS:** Pretty easy.
   **CONS:** Could be tricky for Markdown links in our legal docs, since we'd have to put raw HTML in there instead of Markdown links.
2. See if a link starts with `/` or `https://testpilot.firefox.com` and don't show external site icons for those links.
   
   ``` sass
   a[href^="/"],
   a[href^="https://testpilot.firefox.com"] {
   color: red;
   }
   ```
   
   **PROS:** Don't need to change any markup (or markdown).
   **CONS:** Ugly. Wouldn't work for local/dev/stage/prod unless we added those URLs to the Sass as well. Plus it's working backwards, it'd only match URLs which DO start with `/`, or `https://testpilot.firefox.com`, so we'd probably have to apply icons to all links and then hide them for links which are internal.

**Comment by pdehaan** [comment]
Seems like Wikipedia adds a custom `.external {}` class to outbound links:

``` html
<a rel="nofollow" class="external text" href="http://www.nezavisne.com/umjetnost-zabava/jet-set/Zavrseno-crkveno-vjencanje-Novaka-i-Jelene-Djokovic-253237.html">"Završeno crkveno vjenčanje Novaka i Jelene Đoković"</a>
```

Then has some CSS which specifies an data-uri SVG as an offset background-image (plus a few fallbacks):

``` css
.mw-body .external {
    background-position: center right;
    background-repeat: no-repeat;
    background-image: url(/w/skins/Vector/images/external-link-ltr-icon.png?325de);
    background-image: linear-gradient(transparent,transparent),url(data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22…%206.723l2.882-2.88-1.85-1.852z%22%20fill%3D%22%23fff%22%2F%3E%3C%2Fsvg%3E);
    background-image: linear-gradient(transparent,transparent),url(/w/skins/Vector/images/external-link-ltr-icon.svg?13447)!ie;
    background-image: -o-linear-gradient(transparent,transparent),url(/w/skins/Vector/images/external-link-ltr-icon.png?325de);
    padding-right: 13px;
}
```
